# Generated by Django 3.2.8 on 2021-11-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(default='', max_length=500)),
                ('event_token', models.CharField(default='', max_length=500)),
                ('userid', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('privacy', models.BooleanField(default=False)),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('isVirtual', models.BooleanField(default=False)),
                ('location', models.TextField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
