# Generated by Django 3.2.8 on 2021-11-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.TextField(),
        ),
    ]
