# Generated by Django 3.2.8 on 2021-12-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_session_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='usertoken',
            field=models.CharField(default='', max_length=500),
        ),
    ]
