# Generated by Django 3.2.8 on 2021-12-13 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_session_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='users',
            field=models.ManyToManyField(related_name='user_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
