# Generated by Django 3.2.8 on 2022-01-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('sport', models.IntegerField(default=0)),
                ('study', models.IntegerField(default=0)),
                ('meeting', models.IntegerField(default=0)),
                ('work', models.IntegerField(default=0)),
                ('hangout', models.IntegerField(default=0)),
                ('city', models.TextField(default='Not set')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
    ]
