# Generated by Django 3.2.8 on 2021-11-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.CharField(default='', max_length=500)),
                ('task_token', models.CharField(default='', max_length=500)),
                ('userid', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('alarm_check', models.TextField()),
                ('push_notification', models.TextField()),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
