# Generated by Django 3.2.8 on 2021-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_user_id_task_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_token',
            field=models.CharField(default='', max_length=500),
        ),
    ]
