# Generated by Django 3.2.8 on 2021-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
