# Generated by Django 3.2.8 on 2021-11-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='push_alarm',
            field=models.TextField(default='false'),
        ),
        migrations.AlterField(
            model_name='task',
            name='push_notification',
            field=models.TextField(default='false'),
        ),
    ]
